services:
    web:
        build: .
        container_name: 4-Cuts-with-Prof_Backend
        env_file: .env
        environment:
            - SOMETHING_VERY_SPECIAL=${SOMETHING_VERY_SPECIAL}
        ports:
            - "8000:8000"
        volumes:
            -   ./app:/code/app
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
